version: '3.7'

services:
  db:
    container_name: db_lms
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    image: postgres:14.7-alpine
    ports:
      - "5432:5432"

  backend:
    container_name: backend_lms
    build:
      context: ./lms
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    ports:
      - "8000:8000"
